## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [4]:
import torch

## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [6]:
# Get dimension
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# Get dimension
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       
                       [[4, 9, 9], 
                        [0, 2, 9],
                        [8, 1, 9]],
                       
                       [[3, 9, 9],
                        [4, 5, 3],
                        [3, 4, 5]]
                       ])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[4, 9, 9],
         [0, 2, 9],
         [8, 1, 9]],

        [[3, 9, 9],
         [4, 5, 3],
         [3, 4, 5]]])

In [15]:
len(TENSOR)

3

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([3, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR[0].shape

torch.Size([3, 3])

### Random tensors

Why random tensors?

Random tensors are important becasue the way many neural networks learn is that they start with tensors full of random numbers adn then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3, 4) / shape(3, 4) -> size == shape
random_tensor = torch.rand(5, 3, 4)
"""
5x3x4 TENSOR visualizing
[
    1->[
            1  2  3   4
        1->[1, 2, 3, 4],
        2->[5, 6, 7, 8],
        3->[9, 10, 11, 12],
    ],
    
    2->[
            1   2   3   4
        1->[13, 14, 15, 16],
        2->[17, 18, 19, 20],
        3->[21, 22, 23, 24],
    ],
    
    3->[
            1  2  3  4
        1->[0, 0, 0, 0],
        2->[1, 1, 1, 1],
        3->[2, 2, 2, 2],
    ],
    
    4->[
            1  2  3  4
        1->[3, 3, 3, 3],
        2->[4, 4, 4, 4],
        3->[5, 5, 5, 5],            
    ],
    
    5->[
            1  2  3  4
        1->[6, 6, 6, 6],
        2->[7, 7, 7, 7],
        3->[8, 8, 8, 8],
    ],
]

"""

random_tensor

tensor([[[0.0291, 0.0126, 0.4964, 0.5374],
         [0.4959, 0.1349, 0.8851, 0.4474],
         [0.9089, 0.9030, 0.1749, 0.9163]],

        [[0.7399, 0.4727, 0.8327, 0.1583],
         [0.0828, 0.4252, 0.6054, 0.2767],
         [0.2498, 0.4760, 0.4862, 0.1348]],

        [[0.6812, 0.6352, 0.7534, 0.9781],
         [0.1090, 0.0714, 0.4613, 0.5836],
         [0.5502, 0.8920, 0.8119, 0.5488]],

        [[0.8526, 0.3333, 0.6652, 0.4518],
         [0.4947, 0.8033, 0.2580, 0.1769],
         [0.5355, 0.6820, 0.5936, 0.5303]],

        [[0.4605, 0.5857, 0.2425, 0.7213],
         [0.7931, 0.4795, 0.9763, 0.9852],
         [0.2949, 0.0202, 0.4667, 0.5899]]])

In [21]:
random_tensor.ndim

3

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel(R, G, B)
# could also be written as color first
# random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel(R, G, B), height, width

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
len(random_image_size_tensor)

# [ (244[  ])]]

224

In [24]:
random_image_size_tensor[0]

tensor([[0.7270, 0.4034, 0.9732],
        [0.1597, 0.1024, 0.6792],
        [0.0659, 0.9619, 0.6636],
        [0.1648, 0.9772, 0.0360],
        [0.9935, 0.2928, 0.9989],
        [0.6254, 0.3001, 0.1952],
        [0.3166, 0.0781, 0.4886],
        [0.7980, 0.7030, 0.3476],
        [0.7927, 0.7053, 0.0200],
        [0.5008, 0.9826, 0.7377],
        [0.0515, 0.3446, 0.7634],
        [0.9737, 0.2344, 0.4610],
        [0.3411, 0.8795, 0.9680],
        [0.3264, 0.6403, 0.0752],
        [0.1289, 0.7402, 0.4497],
        [0.5911, 0.8050, 0.4398],
        [0.8680, 0.9392, 0.2724],
        [0.0636, 0.7364, 0.5026],
        [0.1957, 0.2842, 0.0148],
        [0.5995, 0.6897, 0.0348],
        [0.3983, 0.5052, 0.0502],
        [0.0826, 0.0304, 0.3351],
        [0.3715, 0.8209, 0.6589],
        [0.8318, 0.1929, 0.5835],
        [0.3081, 0.9188, 0.1159],
        [0.4375, 0.1031, 0.8880],
        [0.0826, 0.7931, 0.0947],
        [0.5923, 0.1590, 0.7538],
        [0.0410, 0.4444, 0.9554],
        [0.852

## Zeros and ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# masking
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [27]:
# Createa tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
# datatype
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [30]:
# use torch.range() and get deprecated message,  use torch.arange() instead
one_to_ten = torch.arange(start=1, end=11, step=0.1)
one_to_ten

tensor([ 1.0000,  1.1000,  1.2000,  1.3000,  1.4000,  1.5000,  1.6000,  1.7000,
         1.8000,  1.9000,  2.0000,  2.1000,  2.2000,  2.3000,  2.4000,  2.5000,
         2.6000,  2.7000,  2.8000,  2.9000,  3.0000,  3.1000,  3.2000,  3.3000,
         3.4000,  3.5000,  3.6000,  3.7000,  3.8000,  3.9000,  4.0000,  4.1000,
         4.2000,  4.3000,  4.4000,  4.5000,  4.6000,  4.7000,  4.8000,  4.9000,
         5.0000,  5.1000,  5.2000,  5.3000,  5.4000,  5.5000,  5.6000,  5.7000,
         5.8000,  5.9000,  6.0000,  6.1000,  6.2000,  6.3000,  6.4000,  6.5000,
         6.6000,  6.7000,  6.8000,  6.9000,  7.0000,  7.1000,  7.2000,  7.3000,
         7.4000,  7.5000,  7.6000,  7.7000,  7.8000,  7.9000,  8.0000,  8.1000,
         8.2000,  8.3000,  8.4000,  8.5000,  8.6000,  8.7000,  8.8000,  8.9000,
         9.0000,  9.1000,  9.2000,  9.3000,  9.4000,  9.5000,  9.6000,  9.7000,
         9.8000,  9.9000, 10.0000, 10.1000, 10.2000, 10.3000, 10.4000, 10.5000,
        10.6000, 10.7000, 10.8000, 10.90

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [32]:
len(one_to_ten), len(ten_zeros)

(100, 100)

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learnging: 
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device


- List of all datatypes in PyTorch - https://pytorch.org/docs/stable/tensors.html#data-types
- Precision in computer science - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%precision,used%20to%20express%20a%20value.

TODO: READ ON TENSOR DATATYPES AND PRECISION IN COMPUTER SCIENCE



In [33]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what datatype is the tensor (e.g float32 or float16)
                               device=None, # What device is your on? CPU or GPU(cuda)
                               requires_grad=False # wether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
# converting datatypes in Pytorch
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half == torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
mul = float_16_tensor * float_32_tensor

mul.dtype, float_16_tensor.dtype, float_32_tensor.dtype

(torch.float32, torch.float16, torch.float32)

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

### Getting inforamtion from Tensors (tensor attributes)

1. Tensor not right datatype - to get datatype from a tensor, you can use `tensor.dype`
2. Tensor not right shape - to get shape from a tensor, you can use `tensor.shape`
3. Tensor not on right device - to get device from a tensor, you can use `tensor.device`

In [38]:
# Creat a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4223, 0.3523, 0.6990, 0.7067],
        [0.3275, 0.5222, 0.7151, 0.2746],
        [0.5995, 0.1966, 0.7319, 0.1155]])

**Note:** _size_ and _shape_ of a **tensor** returns the same output but `torch.size()` is a function while `torch.shape` is an attibute 

In [39]:
# demo here ⬇️⬇️⬇️⬇️⬇️
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [42]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4223, 0.3523, 0.6990, 0.7067],
        [0.3275, 0.5222, 0.7151, 0.2746],
        [0.5995, 0.1966, 0.7319, 0.1155]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations incluse:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [49]:
# Create a tensor and add to it

tensor = torch.rand(5, dtype=torch.float16)
tensor + 10

tensor([10.6094, 10.0703, 10.1484, 10.3672, 10.5547], dtype=torch.float16)

In [50]:
# multiply tensor by 10
tensor * 10

tensor([6.0938, 0.7373, 1.4697, 3.6914, 5.5547], dtype=torch.float16)

In [51]:
# Substract 10
tensor - 10

tensor([-9.3906, -9.9297, -9.8516, -9.6328, -9.4453], dtype=torch.float16)

In [52]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([6.0938, 0.7373, 1.4697, 3.6914, 5.5547], dtype=torch.float16)

### Matrix Multiplication

Two main way of performing multiplication in neural network and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

- Matrix multiplication - https://www.mathsisfun.com/algebra/matrix-multiplying.
- resource 2(visualizing) - http://matrixmultiplication.xyz


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must much
    * `(3, 2) @ (3, 2)` won't work ❌❌
    * `(2, 3) @ (3, 2)` will work ✅✅
    * `(3, 2) @ (2, 3)` will work ✅✅
2. The resulting matrix has the shape of the **outer dimension**
    * `(2, 3) @ (3, 2)` -> `(2, 2)`
    * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [57]:
# Element wise multiplication
new_tensor = torch.tensor([1, 2, 3])
print(new_tensor, "*", new_tensor)
print(f"Equals: {new_tensor * new_tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [58]:
# Matrix multiplication
torch.matmul(new_tensor, new_tensor)

tensor(14)

In [59]:
# Marix multiplication by hand
(1 * 1) + (2 * 2) + (3 * 3)

14

In [61]:
%%time
value = 0
for i in range(len(new_tensor)):
    value += new_tensor[i] * new_tensor[i]
    
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 5.44 ms


### TODO: READ ON VECTORIZATION FOR OPTIMIZING CODE

In [62]:
%%time
torch.matmul(new_tensor, new_tensor)

CPU times: total: 0 ns
Wall time: 2.52 ms


tensor(14)

### One of the most common error in deep learning: shape errors

In [64]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.mm(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [65]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shpar of one of the our tensors using `transpose`

A **transpose** switches the axes or dimenson of a given tensor

In [68]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [69]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [73]:
%%time
# The matrix multiplication operation works when the tensor_B is transposed
print(f"Orginal shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must much")
print("Output: \n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Orginal shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must much
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
CPU times: total: 0 ns
Wall time: 5.2 ms


## Finding the min, max, mean, sum etc...(tensor aggregation)

In [79]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [77]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [78]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [83]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 or complex number dtype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [84]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [89]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
# find the position in tensor that has the minimum value with argmin() -> returns the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [90]:
# find the postion in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshaping an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [105]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)

In [106]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [107]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [109]:
# Change thev view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [110]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

Do vstack and hstack

In [113]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [119]:
# torch.squeeze() - removes all single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")


# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [120]:
# torch.unsqueeze() - adds a single dimension to a target at a specific dim(dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [121]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [126]:
x_original[0, 0, 0]= 0.0111
x_original[0,0,0], x_permuted[0,0,0]

(tensor(0.0111), tensor(0.0111))

### Indexing (selecting data from a tensor)

Indexing with PyTorch is similar to indexing with NumPy

In [127]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)

In [129]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [130]:
# let's index on out new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [131]:
# let index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [133]:
# let index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [134]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [138]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [143]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [144]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorh has the functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [145]:
# NumPy array to tensor
import torch
import numpy as np

In [146]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [147]:
# Change the value of array, what will this to to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [148]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [150]:
# Change the value of tensor, what will this to to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random number to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [153]:
import torch

In [154]:
# Crete 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8760, 0.0275, 0.4761, 0.6723],
        [0.6088, 0.8199, 0.7975, 0.2515],
        [0.3248, 0.4903, 0.0232, 0.0914]])
tensor([[0.4718, 0.8379, 0.8674, 0.8603],
        [0.7515, 0.1438, 0.5605, 0.9017],
        [0.4879, 0.6321, 0.9639, 0.4796]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Extra resources for reproducibility
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [156]:
import torch

# Let's make some random but reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to everything hunky dory(good).

### 1.  Getting a GPU

1. Easiest -  Use Google Colab for free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU,  there's lots of options...
3. Use could computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentaton: https://pytorch.org/get-started/locally/

In [158]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices


E.g. run GPU if available, else default to CPU

In [159]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [160]:
# count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU because using GPU results in faster computations

In [162]:
# creat a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# tensor no on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [163]:
# move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [ ]:
# if tensor is on the GPU can't transform it to NumPy
tensor_on_gpu.numpy()

In [ ]:
# to fix the GPU tensor with numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

# Excercies & Extra-curriculum

See excerciesfot this notebook here: https:www.learnpytorch.io/00_pytorch_fundamentals/#exercises