# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
# Import torch
import torch

# Create random tensor
rand1 = torch.rand(7, 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
rand2 = torch.rand(1, 7)

# Perform matrix multiplication 
RAND =  torch.matmul(rand1, rand2.T) # (7 x 7) (1 * 7)
RAND

tensor([[1.7540],
        [0.7726],
        [1.6834],
        [1.7175],
        [1.6798],
        [1.1841],
        [1.6105]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(7, 1)

torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
TEN = torch.matmul(tensor1, tensor2)
TEN


tensor([[0.2463, 0.3812, 0.0439, 0.0655, 0.1526, 0.3147, 0.2432],
        [0.3812, 0.5902, 0.0680, 0.1014, 0.2362, 0.4871, 0.3765],
        [0.0439, 0.0680, 0.0078, 0.0117, 0.0272, 0.0561, 0.0434],
        [0.0655, 0.1014, 0.0117, 0.0174, 0.0406, 0.0837, 0.0647],
        [0.1526, 0.2362, 0.0272, 0.0406, 0.0945, 0.1949, 0.1507],
        [0.3147, 0.4871, 0.0561, 0.0837, 0.1949, 0.4021, 0.3108],
        [0.2432, 0.3765, 0.0434, 0.0647, 0.1507, 0.3108, 0.2402]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
import torch
import numpy as np
import random

def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Set your desired seed
seed = 42
seed_everything(seed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [24]:
# Set random seed
CUDA_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(CUDA_SEED)
tensor_A = torch.rand(2, 3).to(device=device)
torch.manual_seed(CUDA_SEED)
tensor_B = torch.rand(3, 2).to(device=device)

tensor_A, tensor_B


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019],
         [0.2598, 0.3666],
         [0.0583, 0.7006]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [26]:
# Perform matmul on tensor_A and tensor_B
mm = torch.matmul(tensor_A, tensor_B)
mm

tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]])

### 8. Find the maximum and minimum values of the output of 7.

In [39]:
# Find max
max = torch.max(mm, 0)

# Find min
min = mm.min()

max, min

(torch.return_types.max(
 values=tensor([0.1204, 0.6596]),
 indices=tensor([0, 1])),
 tensor(0.0666))

### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
ag_max = mm.argmax()

# Find arg min
ag_min = mm.argmin()

ag_max, ag_min

(tensor(3), tensor(2))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [44]:
# Set seed
seed = 7

# Create random tensor
torch.manual_seed(seed)
random_tensor = torch.rand(1, 1, 1, 10)


# Remove single dimensions
squeezed_tensor = random_tensor.squeeze()


# Print out tensors and their shapes
print(f"""
random tensor -> {random_tensor}
random tensor shape -> {random_tensor.shape}


squeezed tensor -> {squeezed_tensor}
squeezed tensor shape -> {squeezed_tensor.shape}
""")



random tensor -> tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
random tensor shape -> torch.Size([1, 1, 1, 10])


squeezed tensor -> tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
squeezed tensor shape -> torch.Size([10])
      
